-- name: CreateDraft :exec
INSERT INTO drafts ( ID, codigo, tipo, situacao, formato, image_url, description, dataValidade, unidade, pesoLiquido, pesoBruto, volumes, itensPorCaixa, gtin, gtinEmbalagem, tipoProducao, condicao, freteGratis, marca, descricaoComplementar ,linkExterno, observacoes, descricaoEmbalagemDiscreta, source, price, promotion, link, search_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30);

-- name: GetDrafts :many
SELECT ID, 
        codigo, 
        tipo,
        situacao,
        formato,
        image_url,
        description,
        dataValidade,
        unidade,
        pesoLiquido,
        pesoBruto,
        volumes,
        itensPorCaixa,
        gtin,
        gtinEmbalagem,
        tipoProducao,
        condicao,
        freteGratis,
        marca,
        descricaoComplementar,
        linkExterno,
        observacoes ,
        descricaoEmbalagemDiscreta ,
        source,
        price,
        promotion,
        link,
        search_id,
        created_at,
        updated_at
FROM drafts ORDER BY created_at DESC;

-- name: GetDraftByDescription :many
SELECT ID,
        codigo, 
        tipo,
        situacao,
        formato,
        image_url,
        description,
        dataValidade,
        unidade,
        pesoLiquido,
        pesoBruto,
        volumes,
        itensPorCaixa,
        gtin,
        gtinEmbalagem,
        tipoProducao,
        condicao,
        freteGratis,
        marca,
        descricaoComplementar,
        linkExterno,
        observacoes ,
        descricaoEmbalagemDiscreta ,
        source,
        price,
        promotion,
        link,
        search_id,
        created_at,
        updated_at
FROM drafts
WHERE drafts.description LIKE '%' || $1 || '%';

-- name: GetDraft :one
SELECT ID,
        codigo, 
        tipo,
        situacao,
        formato,
        image_url,
        description,
        dataValidade,
        unidade,
        pesoLiquido,
        pesoBruto,
        volumes,
        itensPorCaixa,
        gtin,
        gtinEmbalagem,
        tipoProducao,
        condicao,
        freteGratis,
        marca,
        descricaoComplementar,
        linkExterno,
        observacoes ,
        descricaoEmbalagemDiscreta ,
        source,
        price,
        promotion,
        link,
        search_id,
        created_at,
        updated_at
FROM drafts
WHERE drafts.id = $1;

-- name: GetDraftBySearchId :one
SELECT ID,
        codigo, 
        tipo,
        situacao,
        formato,
        image_url,
        description,
        dataValidade,
        unidade,
        pesoLiquido,
        pesoBruto,
        volumes,
        itensPorCaixa,
        gtin,
        gtinEmbalagem,
        tipoProducao,
        condicao,
        freteGratis,
        marca,
        descricaoComplementar,
        linkExterno,
        observacoes ,
        descricaoEmbalagemDiscreta ,
        source,
        price,
        promotion,
        link,
        search_id,
        created_at,
        updated_at
FROM drafts
WHERE drafts.search_id = $1;

-- name: UpdateDraft :exec
UPDATE drafts SET codigo = $2, 
        tipo = $3,
        situacao = $4,
        formato = $5,
        image_url = $6,
        description = $7,
        dataValidade = $8,
        unidade = $9,
        pesoLiquido = $10,
        pesoBruto = $11,
        volumes = $12,
        itensPorCaixa = $13,
        gtin = $14,
        gtinEmbalagem = $15,
        tipoProducao = $16,
        condicao = $17,
        freteGratis = $18,
        marca = $19,
        descricaoComplementar = $20,
        linkExterno = $21,
        observacoes = $22,
        descricaoEmbalagemDiscreta = $23,
        source = $24,
        price = $25,
        promotion = $26,
        link = $27,
        search_id = $28,
        updated_at = $29
WHERE drafts.id = $1;

-- name: DeleteDraft :exec
DELETE FROM drafts
WHERE drafts.id = $1;

-- name: DeleteDraftBySearchID :exec
DELETE FROM drafts
WHERE drafts.search_id = $1;
