// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: commission.sql

package db

import (
	"context"
	"time"
)

const createCommission = `-- name: CreateCommission :exec
INSERT INTO commissions (items_sales_order_id, base, aliquota, valor, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateCommissionParams struct {
	ItemsSalesOrderID int64     `json:"items_sales_order_id"`
	Base              float64   `json:"base"`
	Aliquota          float64   `json:"aliquota"`
	Valor             float64   `json:"valor"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

func (q *Queries) CreateCommission(ctx context.Context, arg CreateCommissionParams) error {
	_, err := q.db.ExecContext(ctx, createCommission,
		arg.ItemsSalesOrderID,
		arg.Base,
		arg.Aliquota,
		arg.Valor,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
