// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: draft.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createDraft = `-- name: CreateDraft :exec
INSERT INTO drafts ( ID, codigo, tipo, situacao, formato, image_url, description, dataValidade, unidade, pesoLiquido, pesoBruto, volumes, itensPorCaixa, gtin, gtinEmbalagem, tipoProducao, condicao, freteGratis, marca, descricaoComplementar ,linkExterno, observacoes, descricaoEmbalagemDiscreta, source, price, promotion, link, search_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30)
`

type CreateDraftParams struct {
	ID                         uuid.UUID `json:"id"`
	Codigo                     string    `json:"codigo"`
	Tipo                       string    `json:"tipo"`
	Situacao                   string    `json:"situacao"`
	Formato                    string    `json:"formato"`
	ImageUrl                   string    `json:"image_url"`
	Description                string    `json:"description"`
	Datavalidade               time.Time `json:"datavalidade"`
	Unidade                    string    `json:"unidade"`
	Pesoliquido                float64   `json:"pesoliquido"`
	Pesobruto                  float64   `json:"pesobruto"`
	Volumes                    int32     `json:"volumes"`
	Itensporcaixa              int32     `json:"itensporcaixa"`
	Gtin                       string    `json:"gtin"`
	Gtinembalagem              string    `json:"gtinembalagem"`
	Tipoproducao               string    `json:"tipoproducao"`
	Condicao                   int32     `json:"condicao"`
	Fretegratis                bool      `json:"fretegratis"`
	Marca                      string    `json:"marca"`
	Descricaocomplementar      string    `json:"descricaocomplementar"`
	Linkexterno                string    `json:"linkexterno"`
	Observacoes                string    `json:"observacoes"`
	Descricaoembalagemdiscreta string    `json:"descricaoembalagemdiscreta"`
	Source                     string    `json:"source"`
	Price                      float64   `json:"price"`
	Promotion                  bool      `json:"promotion"`
	Link                       string    `json:"link"`
	SearchID                   uuid.UUID `json:"search_id"`
	CreatedAt                  time.Time `json:"created_at"`
	UpdatedAt                  time.Time `json:"updated_at"`
}

func (q *Queries) CreateDraft(ctx context.Context, arg CreateDraftParams) error {
	_, err := q.db.ExecContext(ctx, createDraft,
		arg.ID,
		arg.Codigo,
		arg.Tipo,
		arg.Situacao,
		arg.Formato,
		arg.ImageUrl,
		arg.Description,
		arg.Datavalidade,
		arg.Unidade,
		arg.Pesoliquido,
		arg.Pesobruto,
		arg.Volumes,
		arg.Itensporcaixa,
		arg.Gtin,
		arg.Gtinembalagem,
		arg.Tipoproducao,
		arg.Condicao,
		arg.Fretegratis,
		arg.Marca,
		arg.Descricaocomplementar,
		arg.Linkexterno,
		arg.Observacoes,
		arg.Descricaoembalagemdiscreta,
		arg.Source,
		arg.Price,
		arg.Promotion,
		arg.Link,
		arg.SearchID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteDraft = `-- name: DeleteDraft :exec
DELETE FROM drafts
WHERE drafts.id = $1
`

func (q *Queries) DeleteDraft(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDraft, id)
	return err
}

const deleteDraftBySearchID = `-- name: DeleteDraftBySearchID :exec
DELETE FROM drafts
WHERE drafts.search_id = $1
`

func (q *Queries) DeleteDraftBySearchID(ctx context.Context, searchID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDraftBySearchID, searchID)
	return err
}

const getDraft = `-- name: GetDraft :one
SELECT ID,
        codigo, 
        tipo,
        situacao,
        formato,
        image_url,
        description,
        dataValidade,
        unidade,
        pesoLiquido,
        pesoBruto,
        volumes,
        itensPorCaixa,
        gtin,
        gtinEmbalagem,
        tipoProducao,
        condicao,
        freteGratis,
        marca,
        descricaoComplementar,
        linkExterno,
        observacoes ,
        descricaoEmbalagemDiscreta ,
        source,
        price,
        promotion,
        link,
        search_id,
        created_at,
        updated_at
FROM drafts
WHERE drafts.id = $1
`

func (q *Queries) GetDraft(ctx context.Context, id uuid.UUID) (Draft, error) {
	row := q.db.QueryRowContext(ctx, getDraft, id)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.Codigo,
		&i.Tipo,
		&i.Situacao,
		&i.Formato,
		&i.ImageUrl,
		&i.Description,
		&i.Datavalidade,
		&i.Unidade,
		&i.Pesoliquido,
		&i.Pesobruto,
		&i.Volumes,
		&i.Itensporcaixa,
		&i.Gtin,
		&i.Gtinembalagem,
		&i.Tipoproducao,
		&i.Condicao,
		&i.Fretegratis,
		&i.Marca,
		&i.Descricaocomplementar,
		&i.Linkexterno,
		&i.Observacoes,
		&i.Descricaoembalagemdiscreta,
		&i.Source,
		&i.Price,
		&i.Promotion,
		&i.Link,
		&i.SearchID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDraftByDescription = `-- name: GetDraftByDescription :many
SELECT ID,
        codigo, 
        tipo,
        situacao,
        formato,
        image_url,
        description,
        dataValidade,
        unidade,
        pesoLiquido,
        pesoBruto,
        volumes,
        itensPorCaixa,
        gtin,
        gtinEmbalagem,
        tipoProducao,
        condicao,
        freteGratis,
        marca,
        descricaoComplementar,
        linkExterno,
        observacoes ,
        descricaoEmbalagemDiscreta ,
        source,
        price,
        promotion,
        link,
        search_id,
        created_at,
        updated_at
FROM drafts
WHERE drafts.description LIKE '%' || $1 || '%'
`

func (q *Queries) GetDraftByDescription(ctx context.Context, dollar_1 sql.NullString) ([]Draft, error) {
	rows, err := q.db.QueryContext(ctx, getDraftByDescription, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Draft
	for rows.Next() {
		var i Draft
		if err := rows.Scan(
			&i.ID,
			&i.Codigo,
			&i.Tipo,
			&i.Situacao,
			&i.Formato,
			&i.ImageUrl,
			&i.Description,
			&i.Datavalidade,
			&i.Unidade,
			&i.Pesoliquido,
			&i.Pesobruto,
			&i.Volumes,
			&i.Itensporcaixa,
			&i.Gtin,
			&i.Gtinembalagem,
			&i.Tipoproducao,
			&i.Condicao,
			&i.Fretegratis,
			&i.Marca,
			&i.Descricaocomplementar,
			&i.Linkexterno,
			&i.Observacoes,
			&i.Descricaoembalagemdiscreta,
			&i.Source,
			&i.Price,
			&i.Promotion,
			&i.Link,
			&i.SearchID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDraftBySearchId = `-- name: GetDraftBySearchId :one
SELECT ID,
        codigo, 
        tipo,
        situacao,
        formato,
        image_url,
        description,
        dataValidade,
        unidade,
        pesoLiquido,
        pesoBruto,
        volumes,
        itensPorCaixa,
        gtin,
        gtinEmbalagem,
        tipoProducao,
        condicao,
        freteGratis,
        marca,
        descricaoComplementar,
        linkExterno,
        observacoes ,
        descricaoEmbalagemDiscreta ,
        source,
        price,
        promotion,
        link,
        search_id,
        created_at,
        updated_at
FROM drafts
WHERE drafts.search_id = $1
`

func (q *Queries) GetDraftBySearchId(ctx context.Context, searchID uuid.UUID) (Draft, error) {
	row := q.db.QueryRowContext(ctx, getDraftBySearchId, searchID)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.Codigo,
		&i.Tipo,
		&i.Situacao,
		&i.Formato,
		&i.ImageUrl,
		&i.Description,
		&i.Datavalidade,
		&i.Unidade,
		&i.Pesoliquido,
		&i.Pesobruto,
		&i.Volumes,
		&i.Itensporcaixa,
		&i.Gtin,
		&i.Gtinembalagem,
		&i.Tipoproducao,
		&i.Condicao,
		&i.Fretegratis,
		&i.Marca,
		&i.Descricaocomplementar,
		&i.Linkexterno,
		&i.Observacoes,
		&i.Descricaoembalagemdiscreta,
		&i.Source,
		&i.Price,
		&i.Promotion,
		&i.Link,
		&i.SearchID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDrafts = `-- name: GetDrafts :many
SELECT ID, 
        codigo, 
        tipo,
        situacao,
        formato,
        image_url,
        description,
        dataValidade,
        unidade,
        pesoLiquido,
        pesoBruto,
        volumes,
        itensPorCaixa,
        gtin,
        gtinEmbalagem,
        tipoProducao,
        condicao,
        freteGratis,
        marca,
        descricaoComplementar,
        linkExterno,
        observacoes ,
        descricaoEmbalagemDiscreta ,
        source,
        price,
        promotion,
        link,
        search_id,
        created_at,
        updated_at
FROM drafts ORDER BY created_at DESC
`

func (q *Queries) GetDrafts(ctx context.Context) ([]Draft, error) {
	rows, err := q.db.QueryContext(ctx, getDrafts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Draft
	for rows.Next() {
		var i Draft
		if err := rows.Scan(
			&i.ID,
			&i.Codigo,
			&i.Tipo,
			&i.Situacao,
			&i.Formato,
			&i.ImageUrl,
			&i.Description,
			&i.Datavalidade,
			&i.Unidade,
			&i.Pesoliquido,
			&i.Pesobruto,
			&i.Volumes,
			&i.Itensporcaixa,
			&i.Gtin,
			&i.Gtinembalagem,
			&i.Tipoproducao,
			&i.Condicao,
			&i.Fretegratis,
			&i.Marca,
			&i.Descricaocomplementar,
			&i.Linkexterno,
			&i.Observacoes,
			&i.Descricaoembalagemdiscreta,
			&i.Source,
			&i.Price,
			&i.Promotion,
			&i.Link,
			&i.SearchID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDraft = `-- name: UpdateDraft :exec
UPDATE drafts SET codigo = $2, 
        tipo = $3,
        situacao = $4,
        formato = $5,
        image_url = $6,
        description = $7,
        dataValidade = $8,
        unidade = $9,
        pesoLiquido = $10,
        pesoBruto = $11,
        volumes = $12,
        itensPorCaixa = $13,
        gtin = $14,
        gtinEmbalagem = $15,
        tipoProducao = $16,
        condicao = $17,
        freteGratis = $18,
        marca = $19,
        descricaoComplementar = $20,
        linkExterno = $21,
        observacoes = $22,
        descricaoEmbalagemDiscreta = $23,
        source = $24,
        price = $25,
        promotion = $26,
        link = $27,
        search_id = $28,
        updated_at = $29
WHERE drafts.id = $1
`

type UpdateDraftParams struct {
	ID                         uuid.UUID `json:"id"`
	Codigo                     string    `json:"codigo"`
	Tipo                       string    `json:"tipo"`
	Situacao                   string    `json:"situacao"`
	Formato                    string    `json:"formato"`
	ImageUrl                   string    `json:"image_url"`
	Description                string    `json:"description"`
	Datavalidade               time.Time `json:"datavalidade"`
	Unidade                    string    `json:"unidade"`
	Pesoliquido                float64   `json:"pesoliquido"`
	Pesobruto                  float64   `json:"pesobruto"`
	Volumes                    int32     `json:"volumes"`
	Itensporcaixa              int32     `json:"itensporcaixa"`
	Gtin                       string    `json:"gtin"`
	Gtinembalagem              string    `json:"gtinembalagem"`
	Tipoproducao               string    `json:"tipoproducao"`
	Condicao                   int32     `json:"condicao"`
	Fretegratis                bool      `json:"fretegratis"`
	Marca                      string    `json:"marca"`
	Descricaocomplementar      string    `json:"descricaocomplementar"`
	Linkexterno                string    `json:"linkexterno"`
	Observacoes                string    `json:"observacoes"`
	Descricaoembalagemdiscreta string    `json:"descricaoembalagemdiscreta"`
	Source                     string    `json:"source"`
	Price                      float64   `json:"price"`
	Promotion                  bool      `json:"promotion"`
	Link                       string    `json:"link"`
	SearchID                   uuid.UUID `json:"search_id"`
	UpdatedAt                  time.Time `json:"updated_at"`
}

func (q *Queries) UpdateDraft(ctx context.Context, arg UpdateDraftParams) error {
	_, err := q.db.ExecContext(ctx, updateDraft,
		arg.ID,
		arg.Codigo,
		arg.Tipo,
		arg.Situacao,
		arg.Formato,
		arg.ImageUrl,
		arg.Description,
		arg.Datavalidade,
		arg.Unidade,
		arg.Pesoliquido,
		arg.Pesobruto,
		arg.Volumes,
		arg.Itensporcaixa,
		arg.Gtin,
		arg.Gtinembalagem,
		arg.Tipoproducao,
		arg.Condicao,
		arg.Fretegratis,
		arg.Marca,
		arg.Descricaocomplementar,
		arg.Linkexterno,
		arg.Observacoes,
		arg.Descricaoembalagemdiscreta,
		arg.Source,
		arg.Price,
		arg.Promotion,
		arg.Link,
		arg.SearchID,
		arg.UpdatedAt,
	)
	return err
}
