// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: items_sales_order.sql

package db

import (
	"context"
	"time"
)

const createItemsSalesOrder = `-- name: CreateItemsSalesOrder :exec
INSERT INTO items_sales_orders (id, sales_order_id, codigo, unidade, quantidade, desconto, valor, aliquotaIPI, descricao, descricaoDetalhada, product_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type CreateItemsSalesOrderParams struct {
	ID                 int64     `json:"id"`
	SalesOrderID       int64     `json:"sales_order_id"`
	Codigo             string    `json:"codigo"`
	Unidade            string    `json:"unidade"`
	Quantidade         int32     `json:"quantidade"`
	Desconto           float64   `json:"desconto"`
	Valor              float64   `json:"valor"`
	Aliquotaipi        float64   `json:"aliquotaipi"`
	Descricao          string    `json:"descricao"`
	Descricaodetalhada string    `json:"descricaodetalhada"`
	ProductID          int64     `json:"product_id"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}

func (q *Queries) CreateItemsSalesOrder(ctx context.Context, arg CreateItemsSalesOrderParams) error {
	_, err := q.db.ExecContext(ctx, createItemsSalesOrder,
		arg.ID,
		arg.SalesOrderID,
		arg.Codigo,
		arg.Unidade,
		arg.Quantidade,
		arg.Desconto,
		arg.Valor,
		arg.Aliquotaipi,
		arg.Descricao,
		arg.Descricaodetalhada,
		arg.ProductID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getItemsSalesOrderByID = `-- name: GetItemsSalesOrderByID :one
SELECT item.id,
       item.sales_order_id,
       item.codigo,
       item.unidade,
       item.quantidade,
       item.desconto,
       item.valor,
       item.aliquotaIPI,
       item.descricao,
       item.descricaoDetalhada,
       item.product_id,
       item.created_at,
       item.updated_at
FROM items_sales_orders item WHERE item.id = $1
`

func (q *Queries) GetItemsSalesOrderByID(ctx context.Context, id int64) (ItemsSalesOrder, error) {
	row := q.db.QueryRowContext(ctx, getItemsSalesOrderByID, id)
	var i ItemsSalesOrder
	err := row.Scan(
		&i.ID,
		&i.SalesOrderID,
		&i.Codigo,
		&i.Unidade,
		&i.Quantidade,
		&i.Desconto,
		&i.Valor,
		&i.Aliquotaipi,
		&i.Descricao,
		&i.Descricaodetalhada,
		&i.ProductID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItemsSalesOrderByProductID = `-- name: GetItemsSalesOrderByProductID :one
SELECT item.id,
       item.sales_order_id,
       item.codigo,
       item.unidade,
       item.quantidade,
       item.desconto,
       item.valor,
       item.aliquotaIPI,
       item.descricao,
       item.descricaoDetalhada,
       item.product_id,
       item.created_at,
       item.updated_at
FROM items_sales_orders item WHERE item.product_id = $1
`

func (q *Queries) GetItemsSalesOrderByProductID(ctx context.Context, productID int64) (ItemsSalesOrder, error) {
	row := q.db.QueryRowContext(ctx, getItemsSalesOrderByProductID, productID)
	var i ItemsSalesOrder
	err := row.Scan(
		&i.ID,
		&i.SalesOrderID,
		&i.Codigo,
		&i.Unidade,
		&i.Quantidade,
		&i.Desconto,
		&i.Valor,
		&i.Aliquotaipi,
		&i.Descricao,
		&i.Descricaodetalhada,
		&i.ProductID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItemsSalesOrderBySalesOrderID = `-- name: GetItemsSalesOrderBySalesOrderID :one
SELECT item.id,
       item.sales_order_id,
       item.codigo,
       item.unidade,
       item.quantidade,
       item.desconto,
       item.valor,
       item.aliquotaIPI,
       item.descricao,
       item.descricaoDetalhada,
       item.product_id,
       item.created_at,
       item.updated_at
FROM items_sales_orders item WHERE item.sales_order_id = $1
`

func (q *Queries) GetItemsSalesOrderBySalesOrderID(ctx context.Context, salesOrderID int64) (ItemsSalesOrder, error) {
	row := q.db.QueryRowContext(ctx, getItemsSalesOrderBySalesOrderID, salesOrderID)
	var i ItemsSalesOrder
	err := row.Scan(
		&i.ID,
		&i.SalesOrderID,
		&i.Codigo,
		&i.Unidade,
		&i.Quantidade,
		&i.Desconto,
		&i.Valor,
		&i.Aliquotaipi,
		&i.Descricao,
		&i.Descricaodetalhada,
		&i.ProductID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
