// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: person.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPerson = `-- name: CreatePerson :exec
INSERT INTO people ( ID, first_name, last_name, email, phone, cell_phone, personable_id, personable_type, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreatePersonParams struct {
	ID             uuid.UUID      `json:"id"`
	FirstName      string         `json:"first_name"`
	LastName       string         `json:"last_name"`
	Email          string         `json:"email"`
	Phone          sql.NullString `json:"phone"`
	CellPhone      string         `json:"cell_phone"`
	PersonableID   uuid.UUID      `json:"personable_id"`
	PersonableType string         `json:"personable_type"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) error {
	_, err := q.db.ExecContext(ctx, createPerson,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.CellPhone,
		arg.PersonableID,
		arg.PersonableType,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deletePerson = `-- name: DeletePerson :exec
DELETE FROM people
WHERE people.personable_id = $1
`

func (q *Queries) DeletePerson(ctx context.Context, personableID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePerson, personableID)
	return err
}

const getPerson = `-- name: GetPerson :one
SELECT id, first_name, last_name, email, phone, cell_phone, personable_id, personable_type, created_at, updated_at
FROM people
WHERE people.personable_id = $1
`

func (q *Queries) GetPerson(ctx context.Context, personableID uuid.UUID) (Person, error) {
	row := q.db.QueryRowContext(ctx, getPerson, personableID)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.CellPhone,
		&i.PersonableID,
		&i.PersonableType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePerson = `-- name: UpdatePerson :exec
UPDATE people SET first_name = $2, last_name = $3, email = $4, phone = $5, cell_phone = $6, updated_at = $7 WHERE personable_id = $1
`

type UpdatePersonParams struct {
	PersonableID uuid.UUID      `json:"personable_id"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	Email        string         `json:"email"`
	Phone        sql.NullString `json:"phone"`
	CellPhone    string         `json:"cell_phone"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

func (q *Queries) UpdatePerson(ctx context.Context, arg UpdatePersonParams) error {
	_, err := q.db.ExecContext(ctx, updatePerson,
		arg.PersonableID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.CellPhone,
		arg.UpdatedAt,
	)
	return err
}
