// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: stock.sql

package db

import (
	"context"
	"time"
)

const createStock = `-- name: CreateStock :exec
INSERT INTO stocks (product_id, saldo_fisico_total, saldo_virtual_total, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateStockParams struct {
	ProductID         int64     `json:"product_id"`
	SaldoFisicoTotal  int32     `json:"saldo_fisico_total"`
	SaldoVirtualTotal int32     `json:"saldo_virtual_total"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

func (q *Queries) CreateStock(ctx context.Context, arg CreateStockParams) error {
	_, err := q.db.ExecContext(ctx, createStock,
		arg.ProductID,
		arg.SaldoFisicoTotal,
		arg.SaldoVirtualTotal,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getStocks = `-- name: GetStocks :many
SELECT product_id,
        saldo_fisico_total,
        saldo_virtual_total,
        created_at,
        updated_at
FROM stocks
`

func (q *Queries) GetStocks(ctx context.Context) ([]Stock, error) {
	rows, err := q.db.QueryContext(ctx, getStocks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stock
	for rows.Next() {
		var i Stock
		if err := rows.Scan(
			&i.ProductID,
			&i.SaldoFisicoTotal,
			&i.SaldoVirtualTotal,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStock = `-- name: UpdateStock :exec
UPDATE stocks SET saldo_fisico_total = $2, 
  saldo_virtual_total = $3, 
  updated_at = $4
WHERE stocks.product_id = $1
`

type UpdateStockParams struct {
	ProductID         int64     `json:"product_id"`
	SaldoFisicoTotal  int32     `json:"saldo_fisico_total"`
	SaldoVirtualTotal int32     `json:"saldo_virtual_total"`
	UpdatedAt         time.Time `json:"updated_at"`
}

func (q *Queries) UpdateStock(ctx context.Context, arg UpdateStockParams) error {
	_, err := q.db.ExecContext(ctx, updateStock,
		arg.ProductID,
		arg.SaldoFisicoTotal,
		arg.SaldoVirtualTotal,
		arg.UpdatedAt,
	)
	return err
}
